global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'tenantadmin-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'customer-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'vehicle-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'workorder-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['host.docker.internal:8085']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'payment-service'
    static_configs:
      - targets: ['host.docker.internal:8086']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'appointment-service'
    static_configs:
      - targets: ['host.docker.internal:8087']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'file-service'
    static_configs:
      - targets: ['host.docker.internal:8088']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'audit-service'
    static_configs:
      - targets: ['host.docker.internal:8089']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:8090']
    metrics_path: '/actuator/prometheus'
  
  - job_name: 'query-bff-service'
    static_configs:
      - targets: ['host.docker.internal:8091']
    metrics_path: '/actuator/prometheus'
