apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autorepairshop-dev

resources:
  - namespace.yaml
  - postgres.yaml
  - kafka.yaml
  - keycloak.yaml
  - minio.yaml
  - workorder-service.yaml
  - customer-service.yaml
  - gateway-service.yaml
  - tenantadmin-service.yaml
  - vehicle-service.yaml
  - inventory-service.yaml
  - payment-service.yaml
  - appointment-service.yaml
  - file-service.yaml
  - audit-service.yaml
  - notification-service.yaml
  - query-bff-service.yaml

commonLabels:
  app.kubernetes.io/part-of: autorepairshop
  app.kubernetes.io/managed-by: kustomize
